src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="user")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected int $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private string $username;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private string $username_canonical;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private string $email_canonical;

    /**
     * @ORM\Column(type="boolean")
     */
    private bool $enabled = true;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private string $password;

    /**
     * @Assert\Length(min=8)
     * @Assert\Regex(
     *     pattern="/[a-z]/",
     *     message="Your password must contain at least one lowercase letter"
     * )
     * @Assert\Regex(
     *     pattern="/[A-Z]/",
     *     message="Your password must contain at least one uppercase letter"
     * )
     * @Assert\Regex(
     *     pattern="/\d/",
     *     message="Your password must contain at least one digit"
     * )
     * @Assert\Regex(
     *     pattern="/[^a-zA-Z0-9]/",
     *     message="Your password must contain at least one special character"
     * )
     * @Assert\Regex(
     *     pattern="/ /",
     *     match=false,
     *     message="Your password cannot contain spaces"
     * )
     * @Assert\NotCompromisedPassword()
     */
    private ?string $plainPassword = null;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private string $email;

    /**
     * @ORM\Column(name="name", type="string", nullable=false)
     */
    private string $name;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private ?DateTime $registrationDate;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private ?DateTime $emailVerificationDate;

    /**
     * @ORM\Column(type="string", length=128, nullable=true)
     */
    private ?string $resetPasswordToken;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private ?DateTime $resetPasswordTokenTime;

    /**
     * @ORM\Column(type="array")
     */
    private array $roles = [];

    public function __construct()
    {
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function setId($id): static
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return string
     */
    public function getUserIdentifier(): string
    {
        return $this->username;
    }

    /**
     * @param string $username
     * @return User
     */
    public function setUsername(string $username): static
    {
        $this->username = $username;
        return $this;
    }

    /**
     * @return string
     */
    public function getUsernameCanonical(): string
    {
        return $this->username_canonical;
    }

    /**
     * @param string $username_canonical
     * @return User
     */
    public function setUsernameCanonical(string $username_canonical): static
    {
        $this->username_canonical = $username_canonical;
        return $this;
    }

    /**
     * @return string
     */
    public function getEmailCanonical(): string
    {
        return $this->email_canonical;
    }

    /**
     * @param string $email_canonical
     * @return User
     */
    public function setEmailCanonical(string $email_canonical): static
    {
        $this->email_canonical = $email_canonical;
        return $this;
    }

    /**
     * @return bool
     */
    public function getEnabled(): bool
    {
        return $this->enabled;
    }

    /**
     * @param bool $enabled
     * @return User
     */
    public function setEnabled(bool $enabled): User
    {
        $this->enabled = $enabled;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    /**
     * @param string|null $plainPassword
     * @return User
     */
    public function setPlainPassword(?string $plainPassword): User
    {
        $this->plainPassword = $plainPassword;
        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    /**
     * @param string $password
     * @return User
     */
    public function setPassword(string $password): static
    {
        $this->password = $password;
        return $this;
    }

    /**
     * @return string
     */
    public function getEmail(): string
    {
        return $this->email;
    }

    /**
     * @param string $email
     * @return User
     */
    public function setEmail(string $email): static
    {
        $this->email = $email;
        return $this;
    }

    /**
     * @return array
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        return array_unique($roles);
    }

    /**
     * @param array $roles
     * @return User
     */
    public function setRoles(array $roles): User
    {
        $this->roles = $roles;
        return $this;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return User
     */
    public function setName(string $name): static
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return DateTime|null
     */
    public function getEmailVerificationDate(): ?DateTime
    {
        return $this->emailVerificationDate;
    }

    /**
     * @param DateTime|null $emailVerificationDate
     * @return User
     */
    public function setEmailVerificationDate(?DateTime $emailVerificationDate): static
    {
        $this->emailVerificationDate = $emailVerificationDate;
        return $this;
    }

    /**
     * @return DateTime|null
     */
    public function getRegistrationDate(): ?DateTime
    {
        return $this->registrationDate;
    }

    /**
     * @param DateTime|null $registrationDate
     * @return User
     */
    public function setRegistrationDate(?DateTime $registrationDate): static
    {
        $this->registrationDate = $registrationDate;
        return $this;
    }

    /**
     * @return DateTime|null
     */
    public function getResetPasswordTokenTime(): ?DateTime
    {
        return $this->resetPasswordTokenTime;
    }

    /**
     * @param DateTime|null $resetPasswordTokenTime
     * @return User
     */
    public function setResetPasswordTokenTime(?DateTime $resetPasswordTokenTime): static
    {
        $this->resetPasswordTokenTime = $resetPasswordTokenTime;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getResetPasswordToken(): ?string
    {
        return $this->resetPasswordToken;
    }

    /**
     * @param string|null $resetPasswordToken
     * @return User
     */
    public function setResetPasswordToken(?string $resetPasswordToken): static
    {
        $this->resetPasswordToken = $resetPasswordToken;
        return $this;
    }

    /**
     * @return ?string
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
    }

    public function __call(string $name, array $arguments)
    {
    }
}

templates/partials/_bottom_scripts.html.twig
<script src="{{ asset('assets/js/fa.js') }}"></script>
<script src="{{ asset('assets/js/jquery-3.7.0.min.js') }}"></script>
<script src="{{ asset('assets/js/toastr.min.js') }}"></script>
<script src="{{ asset('assets/js/app.js') }}"></script>

{% if app.session.flashbag.peekAll()|length %}
    <script>
        $(document).ready(function () {
            {% for type, messages in app.session.flashbag.all() %}
            {% for msg in messages %}
            toastr.{{ type }}("{{ msg|trans }}", '');
            {% endfor %}
        });
    </script>
    {% endfor %}
{% endif %}

templates/partials/_header.html.twig
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="preconnect" href="https://fonts.gstatic.com">

<link href="{{ asset('assets/css/app.css') }}" rel="stylesheet">
<link href="{{ asset('assets/css/toastr.min.css') }}" rel="stylesheet">
<link href="{{ asset('assets/css/css2.css') }}" rel="stylesheet">

templates/partials/_navbar.html.twig
<nav class="navbar navbar-expand navbar-light navbar-bg">
    <a class="sidebar-toggle js-sidebar-toggle">
        <i class="hamburger align-self-center"></i>
    </a>
    <div class="navbar-collapse collapse">
        {% if is_granted('IS_IMPERSONATOR') %}
            <span id="impersonated-text">Impersonated as {{ app.user.usernameCanonical }}</span>
            <a class="btn btn-primary" href="{{ impersonation_exit_path(path('homepage')) }}">Exit impersonation</a>
        {% endif %}
        <ul class="navbar-nav navbar-align">
            {% if app.user is not null %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle d-none d-sm-inline-block" href="#" data-bs-toggle="dropdown">
                        <img src="{{ asset('assets/img/avatar.webp') }}" class="avatar img-fluid rounded me-1"
                             alt="Avatar"/>
                        <span class="text-dark">
                            {{ app.user.name }}
                        </span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-end">
                        <a class="dropdown-item" href="{{ path('user_profile') }}">
                            <i class="fa-solid fa-user"></i>
                            {{ 'Profile' }}
                        </a>
                        <a class="dropdown-item" href="{{ path('logout') }}">
                            <i class="fa-solid fa-arrow-right-from-bracket"></i>
                            <span class="logout">{{ 'Logout' }}</span>
                        </a>
                    </div>
                </li>
            {% else %}
                <div style="margin-right: 10px;">
                    <a href="{{ path('register') }}"
                       class="btn btn-success">{{ 'Register' }}</a>
                </div>
                <div>
                    <a href="{{ path('login') }}"
                       class="btn btn-success">{{ 'Log in' }}</a>
                </div>
            {% endif %}
        </ul>
    </div>
</nav>

templates/partials/_sidebar.html.twig
<nav id="sidebar" class="sidebar js-sidebar">
    <div class="sidebar-content js-simplebar">
        <a class="sidebar-brand" href="{{ path('homepage') }}">
            <span class="align-middle">{{ 'Worms toolkit' }}</span>
        </a>

        <ul class="sidebar-nav">
            <li class="sidebar-header">
                {{ 'Tools' }}
            </li>
            <li class="sidebar-item {{ 'weapon_draw' in app.request.get('_route') ? 'active' : '' }}">
                <a class="sidebar-link" href="{{ path('weapon_draw') }}">
                    <i class="fa-solid fa-rotate"></i>
                    <span class="align-middle">
                        {{ 'Weapons Drawing' }}
                    </span>
                </a>
            </li>
            <li class="sidebar-item {{ 'weapon_list' in app.request.get('_route') ? 'active' : '' }}">
                <a class="sidebar-link" href="{{ path('weapon_list') }}">
                    <i class="fa-solid fa-shield"></i>
                    <span class="align-middle">
                        {{ 'Armoury' }}
                    </span>
                </a>
            </li>
            <li class="sidebar-item {{ 'draw_stats' in app.request.get('_route') ? 'active' : '' }}">
                <a class="sidebar-link" href="{{ path('draw_stats') }}">
                    <i class="fa-solid fa-chart-pie"></i>
                    <span class="align-middle">
                        {{ 'Draw Statistics' }}
                    </span>
                </a>
            </li>
            {% if is_granted('ROLE_ADMIN') %}
                <li class="sidebar-header">
                    {{ 'Administration' }}
                </li>
                <li class="sidebar-item {{ 'user_list' in app.request.get('_route') ? 'active' : '' }}">
                    <a class="sidebar-link" href="{{ path('user_list') }}">
                        <i class="fa-solid fa-users"></i>
                        <span class="align-middle">
                            {{ 'Users' }}
                        </span>
                    </a>
                </li>
                <li class="sidebar-item {{ 'user_logs' in app.request.get('_route') ? 'active' : '' }}">
                    <a class="sidebar-link" href="{{ path('user_logs') }}">
                        <i class="fa-solid fa-user"></i>
                        <span class="align-middle">
                            {{ 'User Logs' }}
                        </span>
                    </a>
                </li>
                <li class="sidebar-item {{ 'weapon_logs' in app.request.get('_route') ? 'active' : '' }}">
                    <a class="sidebar-link" href="{{ path('weapon_logs') }}">
                        <i class="fa-solid fa-shield"></i>
                        <span class="align-middle">
                            {{ 'Weapon Logs' }}
                        </span>
                    </a>
                </li>
                <li class="sidebar-item {{ 'draw_logs' in app.request.get('_route') ? 'active' : '' }}">
                    <a class="sidebar-link" href="{{ path('draw_logs') }}">
                        <i class="fa-solid fa-rotate"></i>
                        <span class="align-middle">
                            {{ 'Draw Logs' }}
                        </span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/partials/_styles.html.twig
<link href="{{ asset('assets/css/app.css') }}" rel="stylesheet">
<link href="{{ asset('assets/css/toastr.min.css') }}" rel="stylesheet">
<link href="{{ asset('assets/css/css2.css') }}" rel="stylesheet">

<link href="{{ asset('assets/css/custom.css') }}" rel="stylesheet">

templates/partials/_styles_datatable.html.twig
<link href="{{ asset('assets/css/jquery.dataTables.min.css') }}" rel="stylesheet">
<link href="{{ asset('assets/css/responsive.dataTables.min.css') }}" rel="stylesheet">